### PR TITLE
Big cleanup

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by Fox32** [comment]
@kevmoo Maybe also add --trust-primitives, vector_math could benefit from it.

**Comment by joelgwebber** [comment]
Hey, sorry I'm so slow about following up on these things. I'm going to assume this all works and just merge it. Should I expect significantly different results? If so, I'll run them again.

**Comment by kevmoo** [comment]
@joelgwebber Let me look one more time. We have a MUCH better Dart box2d library that I might want to link to. Let me take a look

**Comment by kevmoo** [comment]
Just updated the output. Don't re-run. You won't see a lot of improvement.

We need to get the new box2d port in a package – then we'll start having fun.

**Comment by joelgwebber** [comment]
Groovy, just let me know. And don't hesitate to prod me if I fail to respond in a timely fashion :)

**Comment by kevmoo** [comment]
...thanks.

Feel free to merge this, though. It's solid clean-up for the next round.

**Pull request merged**
